### ISSUE TITLE
When I use the command pip install -e python in the triton-cpu folder I get an error

### ISSUE THREAD

**Issue by Mark3123** [triton-lang/triton-cpu#134]
I successfully installed using the command pip install ninja cmake wheel. However, when I used the command pip install -e python in the triton-cpu folder, an error occurred.

triton-cpu/third_party/amd/backend/include']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for triton
Failed to build triton
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (triton)

**Comment by minjang** [comment]
Please carefully follow the install process one more time, described in https://github.com/triton-lang/triton

And, try to give `-vv` option to see where it actually fails.

```
pip install -e python -vv
```

**Comment by Mark3123** [comment]
@minjang Hello, I used the pip install -e python -vv command, but unfortunately an error occurred. The error message is as follows:
File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/home/y/triton-cpu', '-G', 'Ninja', '-DCMAKE_MAKE_PROGRAM=/tmp/pip-build-env-ud89ri4t/overlay/bin/ninja', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DLLVM_ENABLE_WERROR=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/y/triton-cpu/python/triton/_C', '-DTRITON_BUILD_TUTORIALS=OFF', '-DTRITON_BUILD_PYTHON_MODULE=ON', '-DPython3_EXECUTABLE:FILEPATH=/home/y/miniconda3/envs/triton310_env/bin/python', '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON', '-DPYTHON_INCLUDE_DIRS=/home/y/miniconda3/envs/triton310_env/include/python3.10', '-DTRITON_CODEGEN_BACKENDS=nvidia;amd;cpu', '-DTRITON_PLUGIN_DIRS=', '-DPYBIND11_INCLUDE_DIR=/home/y/.triton/pybind11/pybind11-2.13.1/include', '-DLLVM_INCLUDE_DIRS=/home/y/.triton/llvm/llvm-ce80c80d-ubuntu-x64/include', '-DLLVM_LIBRARY_DIR=/home/y/.triton/llvm/llvm-ce80c80d-ubuntu-x64/lib', '-DCMAKE_BUILD_TYPE=TritonRelBuildWithAsserts', '-DJSON_INCLUDE_DIR=/home/y/.triton/json//include', '-DPYBIND11_INCLUDE_DIR=/home/y/.triton/pybind11/pybind11-2.13.1/include', '-DCUPTI_INCLUDE_DIR=/home/y/triton-cpu/third_party/nvidia/backend/include', '-DROCTRACER_INCLUDE_DIR=/home/y/triton-cpu/third_party/amd/backend/include']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  
  × Building editable for triton (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/y/miniconda3/envs/triton310_env/bin/python /home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_editable /tmp/tmp1tjmjdcq
  cwd: /home/y/triton-cpu/python
  Building editable for triton (pyproject.toml) ... error
  ERROR: Failed building editable for triton
Failed to build triton
Remote version of pip: 24.2
Local version of pip:  24.2
Was pip installed by pip? False
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (triton)
Exception information:
Traceback (most recent call last):
  File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 434, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: ERROR: Failed to build installable wheels for some pyproject.toml based projects (triton)
Removed build tracker: '/tmp/pip-build-tracker-u6odjd_3'

**Comment by Mark3123** [comment]
@minjang  Hello, I used the pip install -e python -vv command, but unfortunately an error occurred. The error message is as follows:
 Traceback (most recent call last):
    File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
      return hook(wheel_directory, config_settings, metadata_directory)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 459, in build_editable
      return self._build_with_temp_dir(
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 503, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
      exec(code, locals())
    File "<string>", line 614, in <module>
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 138, in run
      self._create_wheel_file(bdist_wheel)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 341, in _create_wheel_file
      files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 264, in _run_build_commands
      self._run_build_subcommands()
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 291, in _run_build_subcommands
      self.run_command(name)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-f852rlp8/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
      cmd_obj.run()
    File "<string>", line 366, in run
    File "<string>", line 463, in build_extension
    File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/home/y/triton-cpu', '-G', 'Ninja', '-DCMAKE_MAKE_PROGRAM=/tmp/pip-build-env-f852rlp8/overlay/bin/ninja', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DLLVM_ENABLE_WERROR=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/y/triton-cpu/python/triton/_C', '-DTRITON_BUILD_TUTORIALS=OFF', '-DTRITON_BUILD_PYTHON_MODULE=ON', '-DPython3_EXECUTABLE:FILEPATH=/home/y/miniconda3/envs/triton310_env/bin/python', '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON', '-DPYTHON_INCLUDE_DIRS=/home/y/miniconda3/envs/triton310_env/include/python3.10', '-DTRITON_CODEGEN_BACKENDS=nvidia;amd;cpu', '-DTRITON_PLUGIN_DIRS=', '-DPYBIND11_INCLUDE_DIR=/home/y/.triton/pybind11/pybind11-2.13.1/include', '-DLLVM_INCLUDE_DIRS=/home/y/.triton/llvm/llvm-ce80c80d-ubuntu-x64/include', '-DLLVM_LIBRARY_DIR=/home/y/.triton/llvm/llvm-ce80c80d-ubuntu-x64/lib', '-DCMAKE_BUILD_TYPE=TritonRelBuildWithAsserts', '-DJSON_INCLUDE_DIR=/home/y/.triton/json//include', '-DPYBIND11_INCLUDE_DIR=/home/y/.triton/pybind11/pybind11-2.13.1/include', '-DCUPTI_INCLUDE_DIR=/home/y/triton-cpu/third_party/nvidia/backend/include', '-DROCTRACER_INCLUDE_DIR=/home/y/triton-cpu/third_party/amd/backend/include']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  
  × Building editable for triton (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/y/miniconda3/envs/triton310_env/bin/python /home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_editable /tmp/tmpiky1jj44
  cwd: /home/y/triton-cpu/python
  Building editable for triton (pyproject.toml) ... error
  ERROR: Failed building editable for triton
Failed to build triton
Remote version of pip: 24.2
Local version of pip:  24.2
Was pip installed by pip? False
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (triton)
Exception information:
Traceback (most recent call last):
  File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/home/y/miniconda3/envs/triton310_env/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 434, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: ERROR: Failed to build installable wheels for some pyproject.toml based projects (triton)
Removed build tracker: '/tmp/pip-build-tracker-k3_fdhkz'

**Comment by int3** [comment]
I would suggest running the cmake command printed in the stack trace above; that should get you a more useful error message. But as mentioned on the other task, please open these issues against the main repo.
